### ISSUE TITLE
Please re-run conflation

### ISSUE THREAD

**Issue by jharpster** [iandees/tiger-battlegrid#1]
We've noticed that many of the missing roads initially identified have been filled in by the community. Could you please re-run the conflation and update the Tiger 2017 layer in iD? 
Thanks!

**Comment by iandees** [comment]
I re-ran the process, but it turns out I didn't really document how I did it last time, so I ended up with a different process. The different process seems to have generated a whole lot more "missing TIGER".

I'm happy to take feedback and try to improve this, though! At least I know how to reproduce what I did this time, and now we can improve it.
